services:
  # React 앱 (nginx 포함)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    extra_hosts:
      - "docker.host.internal:host-gateway"
